ユーザーフォロー機能の追加
misonog/fjord-books_app pull request #5
Opened 2021-09-12 02:53 UTC by misonog

WIP

2021-09-17 07:25 UTC, komagata requested changes

2021-09-17 07:25 UTC, komagata commented on app/controllers/users_controller.rb
> +  def following
プラクティスの**参考**にある下記を読んで、その通りにCRUD以外のメソッドを使わずに作ってみてください〜

[DHHはどのようにRailsのコントローラを書くのか | POSTD](https://postd.cc/how-dhh-organizes-his-rails-controllers/)

2021-09-17 12:46 UTC, misonog commented on app/controllers/users_controller.rb
> +  def following
@komagata レビューありがとうございます🙏 記事を参考にコントローラーを分割してみました。
お手数ですが、再度レビューをお願いいたします。

2021-09-18 17:45 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-09-18 23:24 UTC, merged